# -*- coding: utf-8 -*-
"""fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LqY6owrAPh8xFdWgz7X3fAomYoIuuLLe

# Credit Card Fraud Detection — Random Forest

**Датасет:** [Kaggle Credit Card Fraud Detection](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud)

284 807 транзакций, из которых только **492 (0.17%) мошеннические** — сильно несбалансированный датасет.

**Сравниваем 3 стратегии балансировки:**
1. `class_weight='balanced'`
2. Random Undersampling
3. SMOTE

**Метрики:** ROC-AUC, Precision-Recall, Confusion Matrix, Calibration Curve

## 1. Установка зависимостей
"""

!pip install -q imbalanced-learn

"""## 2. Импорты"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score, confusion_matrix, classification_report,
    precision_recall_curve, average_precision_score, RocCurveDisplay
)
from sklearn.calibration import CalibrationDisplay
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

RANDOM_STATE = 42
N_ESTIMATORS = 200
MAX_DEPTH = 12
TEST_SIZE = 0.2

print('Библиотеки загружены успешно')

"""## 3. Загрузка датасета



"""

df = pd.read_csv('/content/creditcard.csv')

print(f'Размер датасета: {df.shape}')
print(f'Мошеннических транзакций: {df["Class"].sum()} ({df["Class"].mean()*100:.4f}%)')
print(f'Обычных транзакций: {(df["Class"]==0).sum()}')
df.head()

"""## 4. Анализ дисбаланса классов"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

counts = df['Class'].value_counts()
axes[0].bar(['Normal (0)', 'Fraud (1)'], counts.values, color=['steelblue', 'crimson'])
axes[0].set_title('Распределение классов')
axes[0].set_ylabel('Количество транзакций')
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 1000, str(v), ha='center', fontweight='bold')

axes[1].pie(counts.values, labels=['Normal', 'Fraud'],
            autopct='%1.3f%%', colors=['steelblue', 'crimson'],
            startangle=90)
axes[1].set_title('Доля классов')

plt.tight_layout()
plt.show()

"""Индекс Джинни и энтропия"""

import numpy as np

total = len(df)
p_normal = (df['Class'] == 0).sum() / total
p_fraud  = (df['Class'] == 1).sum() / total

gini = 1 - (p_normal**2 + p_fraud**2)

entropy = -(p_normal * np.log2(p_normal) + p_fraud * np.log2(p_fraud))

print(f"Доля нормальных:     {p_normal:.6f}")
print(f"Доля мошеннических:  {p_fraud:.6f}")
print(f"\nИндекс Джини:  {gini:.6f}")
print(f"Энтропия:      {entropy:.6f}")
# Джини и энтропия внутри каждого класса (идеально чистые узлы)
print("Если узел содержит только нормальные")
p = 1.0
print(f"Джини:    {1 - p**2:.4f}  (0 = идеально чисто)")
print(f"Энтропия: {0:.4f}         (0 = идеально чисто)")

print("\nЕсли узел содержит 50/50")
p = 0.5
gini_50 = 1 - (p**2 + p**2)
entropy_50 = -(p * np.log2(p) + p * np.log2(p))
print(f"Джини:    {gini_50:.4f}  (0.5 = максимальный хаос)")
print(f"Энтропия: {entropy_50:.4f}  (1.0 = максимальный хаос)")

print("\nВесь наш датасет")
print(f"Джини:    {gini:.6f}  (очень чисто — 99.8% один класс)")
print(f"Энтропия: {entropy:.6f}  (очень чисто)")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

p_values = np.linspace(0.001, 0.999, 300)

# Джини
gini_values = 1 - (p_values**2 + (1-p_values)**2)
axes[0].plot(p_values, gini_values, color='steelblue', linewidth=2)
axes[0].axvline(p_fraud, color='crimson', linestyle='--',
                label=f'Наш датасет (p={p_fraud:.4f})')
axes[0].set_xlabel('Доля мошеннических транзакций')
axes[0].set_ylabel('Индекс Джини')
axes[0].set_title('Индекс Джини')
axes[0].legend()

# Энтропия
entropy_values = -(p_values * np.log2(p_values) + (1-p_values) * np.log2(1-p_values))
axes[1].plot(p_values, entropy_values, color='darkorange', linewidth=2)
axes[1].axvline(p_fraud, color='crimson', linestyle='--',
                label=f'Наш датасет (p={p_fraud:.4f})')
axes[1].set_xlabel('Доля мошеннических транзакций')
axes[1].set_ylabel('Энтропия')
axes[1].set_title('Энтропия')
axes[1].legend()

plt.tight_layout()
plt.show()

"""## 5. Подготовка данных"""

X = df.drop(columns=['Class'])
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
)

print(f'Train: {len(X_train)} записей (fraud: {y_train.sum()})')
print(f'Test:  {len(X_test)} записей (fraud: {y_test.sum()})')

"""## 6. Стратегии балансировки"""

def strategy_class_weight(X_train, y_train):
    """Без ресэмплинга — передаём class_weight='balanced' в классификатор."""
    return X_train, y_train, {'class_weight': 'balanced'}


def strategy_undersampling(X_train, y_train):
    """Уменьшаем мажоритарный класс до размера миноритарного."""
    data = pd.concat([X_train, y_train], axis=1)
    majority = data[data['Class'] == 0]
    minority = data[data['Class'] == 1]
    majority_down = resample(majority, replace=False,
                             n_samples=len(minority),
                             random_state=RANDOM_STATE)
    balanced = pd.concat([majority_down, minority])
    return balanced.drop(columns=['Class']), balanced['Class'], {}


def strategy_smote(X_train, y_train):
    """Генерируем синтетические примеры миноритарного класса через SMOTE."""
    sm = SMOTE(random_state=RANDOM_STATE)
    X_res, y_res = sm.fit_resample(X_train, y_train)
    return X_res, y_res, {}


STRATEGIES = {
    'class_weight': strategy_class_weight,
    'undersampling': strategy_undersampling,
    'SMOTE': strategy_smote,
}

print('Стратегии определены')

"""## 7. Обучение моделей

"""

results = {}

for name, strategy_fn in STRATEGIES.items():
    print(f'\n{"="*50}')
    print(f'Стратегия: {name}')
    print(f'{"="*50}')

    X_bal, y_bal, rf_kwargs = strategy_fn(X_train, y_train)
    print(f'  Обучающих примеров: {len(X_bal)} '
          f'(fraud: {y_bal.sum()}, normal: {(y_bal==0).sum()})')

    clf = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        **rf_kwargs
    )
    clf.fit(X_bal, y_bal)

    y_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]

    roc_auc = roc_auc_score(y_test, y_prob)
    ap = average_precision_score(y_test, y_prob)
    cm = confusion_matrix(y_test, y_pred)

    print(f'  ROC-AUC:       {roc_auc:.6f}')
    print(f'  Avg Precision: {ap:.6f}')
    print(f'\n{classification_report(y_test, y_pred, digits=4)}')

    results[name] = dict(
        clf=clf, y_pred=y_pred, y_prob=y_prob,
        roc_auc=roc_auc, ap=ap, cm=cm
    )

print('\nОбучение завершено!')

"""## 8. Сводная таблица метрик"""

summary = pd.DataFrame(
    {name: {'ROC-AUC': r['roc_auc'], 'Avg Precision': r['ap']}
     for name, r in results.items()}
).T

print('=== ИТОГОВОЕ СРАВНЕНИЕ ===' )
display(summary.style.highlight_max(color='green').format('{:.6f}'))

best = summary['ROC-AUC'].idxmax()
print(f'\nЛучшая стратегия по ROC-AUC: {best}')

"""## 9. Матрицы ошибок"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
colors_list = ['Blues', 'Oranges', 'Greens']

for ax, (name, res), cmap in zip(axes, results.items(), colors_list):
    cm = res['cm']
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    fig.colorbar(im, ax=ax)
    ax.set(xticks=[0,1], yticks=[0,1],
           xticklabels=['Normal','Fraud'],
           yticklabels=['Normal','Fraud'],
           xlabel='Predicted', ylabel='True',
           title=f'Confusion Matrix\n({name})')
    thresh = cm.max() / 2
    for i in range(2):
        for j in range(2):
            ax.text(j, i, f'{cm[i,j]:,}', ha='center', va='center',
                    color='white' if cm[i,j] > thresh else 'black', fontsize=14)

plt.tight_layout()
plt.show()

"""## 10. ROC-кривые"""

fig, ax = plt.subplots(figsize=(8, 6))
colors = ['steelblue', 'darkorange', 'forestgreen']

for (name, res), color in zip(results.items(), colors):
    RocCurveDisplay.from_predictions(
        y_test, res['y_prob'],
        name=f"{name} (AUC={res['roc_auc']:.4f})",
        ax=ax, color=color
    )

ax.set_title('ROC-кривые — сравнение стратегий')
ax.legend()
plt.tight_layout()
plt.show()

"""## 11. Precision-Recall кривые"""

fig, ax = plt.subplots(figsize=(8, 6))

for (name, res), color in zip(results.items(), colors):
    prec, rec, _ = precision_recall_curve(y_test, res['y_prob'])
    ax.plot(rec, prec, color=color,
            label=f"{name} (AP={res['ap']:.4f})")

ax.set_xlabel('Recall')
ax.set_ylabel('Precision')
ax.set_title('Precision-Recall кривые')
ax.legend()
plt.tight_layout()
plt.show()

"""## 12. Кривые калибровки"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax, (name, res), color in zip(axes, results.items(), colors):
    CalibrationDisplay.from_predictions(
        y_test, res['y_prob'],
        n_bins=10, name=name, ax=ax, color=color
    )
    ax.set_title(f'Calibration Curve\n({name})')

plt.tight_layout()
plt.show()

"""## 13. Важность признаков (лучшая модель)"""

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
colors = ['steelblue', 'darkorange', 'forestgreen']

for ax, (name, res), color in zip(axes, results.items(), colors):
    clf = res['clf']
    importances = clf.feature_importances_
    indices = np.argsort(importances)[::-1][:15]
    feature_names = list(X.columns)

    ax.bar(range(len(indices)), importances[indices], color=color)
    ax.set_xticks(range(len(indices)))
    ax.set_xticklabels([feature_names[i] for i in indices], rotation=45, ha='right')
    ax.set_title(f'Важность признаков\n({name})')
    ax.set_ylabel('Важность')

plt.suptitle('Топ-15 признаков по стратегиям', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()